"""sources, ingestion runs, coupon status

Revision ID: 1f2b1639c23d
Revises: 71d3354b511b
Create Date: 2026-10-02 14:04:13.666640

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1f2b1639c23d"
down_revision = "71d3354b511b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sources",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=140), nullable=False),
        sa.Column("kind", sa.Enum("csv", "static", name="source_kind"), nullable=False),
        sa.Column(
            "config", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("probe_destinations", sa.Boolean(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_sources_slug"), "sources", ["slug"], unique=True)
    op.create_table(
        "ingestion_runs",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status", sa.Enum("running", "success", "failed", name="run_status"), nullable=False
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fetched", sa.Integer(), nullable=False),
        sa.Column("created", sa.Integer(), nullable=False),
        sa.Column("updated", sa.Integer(), nullable=False),
        sa.Column("skipped", sa.Integer(), nullable=False),
        sa.Column("failed", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ingestion_runs_source_id"), "ingestion_runs", ["source_id"], unique=False
    )
    # op.add_column does NOT auto-create Postgres enum types — do it explicitly.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        sa.Enum("active", "failed", "expired", name="coupon_status").create(bind, checkfirst=True)
    op.add_column(
        "coupons",
        sa.Column(
            "status",
            sa.Enum("active", "failed", "expired", name="coupon_status"),
            server_default="active",
            nullable=False,
        ),
    )
    op.add_column("coupons", sa.Column("source_id", sa.Uuid(), nullable=True))
    op.add_column("coupons", sa.Column("external_id", sa.String(length=255), nullable=True))
    op.add_column("coupons", sa.Column("failure_reason", sa.String(length=255), nullable=True))
    op.add_column(
        "coupons", sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("coupons", sa.Column("content_hash", sa.String(length=64), nullable=True))
    op.create_index(op.f("ix_coupons_content_hash"), "coupons", ["content_hash"], unique=False)
    op.create_index(op.f("ix_coupons_source_id"), "coupons", ["source_id"], unique=False)
    # batch mode so SQLite (dev/test) can also apply this; a no-op wrapper on Postgres.
    with op.batch_alter_table("coupons") as batch_op:
        batch_op.create_foreign_key(
            "fk_coupons_source_id_sources", "sources", ["source_id"], ["id"], ondelete="SET NULL"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("coupons") as batch_op:
        batch_op.drop_constraint("fk_coupons_source_id_sources", type_="foreignkey")
    op.drop_index(op.f("ix_coupons_source_id"), table_name="coupons")
    op.drop_index(op.f("ix_coupons_content_hash"), table_name="coupons")
    op.drop_column("coupons", "content_hash")
    op.drop_column("coupons", "last_checked_at")
    op.drop_column("coupons", "failure_reason")
    op.drop_column("coupons", "external_id")
    op.drop_column("coupons", "source_id")
    op.drop_column("coupons", "status")
    op.drop_index(op.f("ix_ingestion_runs_source_id"), table_name="ingestion_runs")
    op.drop_table("ingestion_runs")
    op.drop_index(op.f("ix_sources_slug"), table_name="sources")
    op.drop_table("sources")
    # ### end Alembic commands ###
