"""user retention: saves, tracking, preferences, alerts

Revision ID: 2381a1c204f9
Revises: 28509f286c88
Create Date: 2026-10-02 14:46:35.728198

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2381a1c204f9"
down_revision = "28509f286c88"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_preferences",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("email_enabled", sa.Boolean(), nullable=False),
        sa.Column("telegram_enabled", sa.Boolean(), nullable=False),
        sa.Column("telegram_chat_id", sa.String(length=64), nullable=True),
        sa.Column("push_enabled", sa.Boolean(), nullable=False),
        sa.Column("push_subscription", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "saved_stores",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "store_id", name="uq_saved_store"),
    )
    op.create_index(op.f("ix_saved_stores_store_id"), "saved_stores", ["store_id"], unique=False)
    op.create_index(op.f("ix_saved_stores_user_id"), "saved_stores", ["user_id"], unique=False)
    op.create_table(
        "saved_coupons",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("coupon_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["coupon_id"], ["coupons.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "coupon_id", name="uq_saved_coupon"),
    )
    op.create_index(
        op.f("ix_saved_coupons_coupon_id"), "saved_coupons", ["coupon_id"], unique=False
    )
    op.create_index(op.f("ix_saved_coupons_user_id"), "saved_coupons", ["user_id"], unique=False)
    op.create_table(
        "tracked_products",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("target_price", sa.Float(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "product_id", name="uq_tracked_product"),
    )
    op.create_index(
        op.f("ix_tracked_products_product_id"), "tracked_products", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_tracked_products_user_id"), "tracked_products", ["user_id"], unique=False
    )
    op.create_table(
        "alert_events",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("tracked_product_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("price_drop", "coupon_appeared", "target_met", name="alert_kind"),
            nullable=False,
        ),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("price_point_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["price_point_id"], ["price_points.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["tracked_product_id"], ["tracked_products.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_alert_events_tracked_product_id"),
        "alert_events",
        ["tracked_product_id"],
        unique=False,
    )
    op.create_index(op.f("ix_alert_events_user_id"), "alert_events", ["user_id"], unique=False)
    op.create_table(
        "track_alert_states",
        sa.Column("tracked_product_id", sa.Uuid(), nullable=False),
        sa.Column("last_price_point_id", sa.Uuid(), nullable=True),
        sa.Column("last_alert_kind", sa.String(length=30), nullable=True),
        sa.Column("alerts_sent", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["last_price_point_id"], ["price_points.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["tracked_product_id"], ["tracked_products.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tracked_product_id", name="uq_track_alert_state"),
    )
    op.create_index(
        op.f("ix_track_alert_states_tracked_product_id"),
        "track_alert_states",
        ["tracked_product_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_track_alert_states_tracked_product_id"), table_name="track_alert_states")
    op.drop_table("track_alert_states")
    op.drop_index(op.f("ix_alert_events_user_id"), table_name="alert_events")
    op.drop_index(op.f("ix_alert_events_tracked_product_id"), table_name="alert_events")
    op.drop_table("alert_events")
    op.drop_index(op.f("ix_tracked_products_user_id"), table_name="tracked_products")
    op.drop_index(op.f("ix_tracked_products_product_id"), table_name="tracked_products")
    op.drop_table("tracked_products")
    op.drop_index(op.f("ix_saved_coupons_user_id"), table_name="saved_coupons")
    op.drop_index(op.f("ix_saved_coupons_coupon_id"), table_name="saved_coupons")
    op.drop_table("saved_coupons")
    op.drop_index(op.f("ix_saved_stores_user_id"), table_name="saved_stores")
    op.drop_index(op.f("ix_saved_stores_store_id"), table_name="saved_stores")
    op.drop_table("saved_stores")
    op.drop_table("notification_preferences")
    # ### end Alembic commands ###
