"""products and price points

Revision ID: 28509f286c88
Revises: b7e3a1c92d44
Create Date: 2026-10-02 14:37:05.248202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28509f286c88'
down_revision = 'b7e3a1c92d44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=True),
    sa.Column('list_price', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('last_captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lowest_price_7d', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=True),
    sa.Column('lowest_price_30d', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=True),
    sa.Column('lowest_price_90d', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=True),
    sa.Column('last_price_drop_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_price_drop_pct', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.create_index(op.f('ix_products_store_id'), 'products', ['store_id'], unique=False)
    op.create_table('price_points',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.Column('original_price', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=True),
    sa.Column('shipping', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('coupon_id', sa.Uuid(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_points_captured_at'), 'price_points', ['captured_at'], unique=False)
    op.create_index(op.f('ix_price_points_product_id'), 'price_points', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_points_product_id'), table_name='price_points')
    op.drop_index(op.f('ix_price_points_captured_at'), table_name='price_points')
    op.drop_table('price_points')
    op.drop_index(op.f('ix_products_store_id'), table_name='products')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
