"""add conversions table

Revision ID: 59be7248d8e7
Revises: a1c9e3f7b251
Create Date: 2026-10-04 01:17:21.198387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59be7248d8e7'
down_revision = 'a1c9e3f7b251'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversions',
    sa.Column('network', sa.String(length=20), nullable=False),
    sa.Column('network_txn_id', sa.String(length=64), nullable=False),
    sa.Column('clickref', sa.String(length=64), nullable=True),
    sa.Column('click_id', sa.Uuid(), nullable=True),
    sa.Column('store_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'declined', 'deleted', name='conversion_status'), nullable=False),
    sa.Column('sale_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('commission_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('transaction_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('click_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decline_reason', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['click_id'], ['click_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversions_click_id'), 'conversions', ['click_id'], unique=False)
    op.create_index(op.f('ix_conversions_clickref'), 'conversions', ['clickref'], unique=False)
    op.create_index('ix_conversions_network_txn', 'conversions', ['network', 'network_txn_id'], unique=True)
    op.create_index('ix_conversions_store_txn', 'conversions', ['store_id', 'transaction_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conversions_store_txn', table_name='conversions')
    op.drop_index('ix_conversions_network_txn', table_name='conversions')
    op.drop_index(op.f('ix_conversions_clickref'), table_name='conversions')
    op.drop_index(op.f('ix_conversions_click_id'), table_name='conversions')
    op.drop_table('conversions')
    # Native enum types are not owned by the table the way an index or a
    # constraint is: `op.drop_table` removes the column that used the type and
    # leaves the type itself behind. Alembic does not track types created inline
    # inside `op.create_table`, so nothing drops them automatically.
    #
    # The consequence of omitting these lines is not a cosmetic leftover. On the
    # next `alembic upgrade head` the upgrade fails with
    # `type "conversion_status" already exists`, which means a deploy cannot be
    # rolled back and then re-applied — the single most expensive thing a migration
    # can fail to do. `IF EXISTS` keeps the downgrade safe against a database where
    # the type was never created (SQLite, where these are plain VARCHARs).
    op.execute('DROP TYPE IF EXISTS conversion_status')
    # ### end Alembic commands ###
